services:
  node:
    container_name: "api-atividade-sesi-listagem"
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3001"
    ports:
      - "3333:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
